#pragma config(Sensor, S1,     lightSensor,    sensorCOLORFULL)
#pragma config(Sensor, S2,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task verificarLinha(){

  while(true){
    if (SensorValue(S1)==BLACKCOLOR){
      motor[motorA] = -100;
      motor[motorB] = -100;
      wait10Msec(100);
    }
  }
}
task procurarInimigo(){
  while(true){
    if (SensorValue(S3)<50){
      motor[motorA] = 50;
      motor[motorB] = 50;
    }

    else{
      motor[motorA] = 50;
      motor[motorB] = -50;
    }
    wait1Msec(100);
  }
}

task main(){
    nMotorEncoderTarget[motorB] = 7;
	  while(true){
	    StartTask(verificarLinha);
	    StartTask(procurarInimigo);
	    StartTask(touchTimer);
	    wait1Msec(10);
	  }
  }
