#pragma config(Sensor, S1,     lightSensor,    sensorCOLORFULL)
#pragma config(Sensor, S2,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task verificarLinha(){

  while(true){
    if (SensorValue(S1)==BLACKCOLOR){
      motor[motorA] = -100;
      motor[motorB] = -100;
      wait10Msec(100);
    }
  }
}
task procurarInimigo(){
  while(true){
    if (SensorValue(S2)<50){
      motor[motorA] = 50;
      motor[motorB] = 50;
    }

    else{
      motor[motorA] = 50;
      motor[motorB] = -50;
    }
    wait1Msec(100);
  }
}
task toque(){
  while(true)
   {
     if(SensorValue(S2) == 1){
         motor[motorA] = 100;
         motor[motorB] = 100;
         motor[motorC] = 100;
     }
      while (SensorValue(S2) == 1)
      {
         if (time10(T1)>500)
         {
            StopTask(lookForLine);
            StopTask(searchForOpponent);
            motor[left] = -50;
            motor[right] = -50;
            wait10Msec(10);
            StartTask(lookForLine);
            StartTask(searchForOpponent);
            ClearTimer(T1);
         }
       }
         wait1Msec(10);
      }
}

task main(){
    nMotorEncoderTarget[motorB] = 7;
	  while(true){
	    StartTask(verificarLinha);
	    StartTask(procurarInimigo);
	    StartTask(toque);
	    wait1Msec(10);
	  }
  }
