#pragma config(Sensor, S1,     lightSensor,    sensorCOLORFULL)
#pragma config(Sensor, S2,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch);
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void verificarLinha(){

    if (SensorValue(S1)==BLACKCOLOR){
      motor[motorA] = -100;
      motor[motorB] = -100;
      wait10Msec(100);
      motor[motorA] = 30;
      motor[motorB] = -30;
      wait10Msec(100);
    };

};
void procurarInimigo(){
  while(SensorValue(S2)==0){
   // if (SensorValue(S2)<50){
     // motor[motorA] = 50;
     // motor[motorB] = 50;
    //}
    //else{
      motor[motorA] = 20;
      motor[motorB] = -20;
    //
    wait1Msec(1000);
  }
}

void toque(){
 // while(true){
     motor[motorA] = 100;
     motor[motorB] = 100;
     if(SensorValue(S3) == 1){
         motor[motorC] = 100;
     }
     wait1Msec(1000);
   //}
}

task main(){
    nMotorEncoderTarget[motorC] = 7;
	  while(true){
	    if(SensorValue(S2)==0){
	      procurarInimigo();
	    }if(SensorValue(S2)>0){
	       if(sensorValue(S1)!=WHITECOLOR){
	          verificarLinha();
	       }
	       if(SensorValue(S2)<50){
	        toque();
	      }
	    }

	    wait1Msec(10);
	  }
  }
